# voting_age=18
# age=16
# if (age>=18):
#     print(f"You are eligible to vote")
# else:
#     print(f"You are not eligible to vote")

# voting_age=18
# age=int(input("Enter your age:"))
# if(age>=18):
#     print(f"You're eligible to vote")
# else:
#     print(f"You're not eligible to vote")


# pwd=500
# user_pwd=int(input("Enter your password:"))
# if(user_pwd == 500):
#     print(f"You are in")
# else:
#     print(f"Stay out")

# num_1=int(input("Enter number A:"))
# num_2=int(input("Enter number B:"))
# product=(num_1*num_2)
# sum=(num_1+num_2)
# print(f"The product of the numbers is{product}")
# print(f"The sum of the numbers is{sum}")

# number=int(input("Enter number:"))
# if(number>10):
#     print(f"Number is greater than 10")
# else:
#     print(f"The number is less tha 10")

# is_logged_in= False
# if(is_logged_in):
#     print(f"You're welcome")
# else:
#     print(f"You're not welcome")


# weekday=str(input("Enter the day of the week:"))
# if weekday in ["Monday","Tuesday","Wednesday","Thursday","Friday"]:
#     print("It is a weekday")
# else:
#     print("It is not a weekday")    

# user_password=int(input("Enter the password"))
# password=5640
# if password == 5640:
#     print("Access granted")
# else:
#     print("Access denied")

# password="Friday"
# password=input("Enter password:")
# if password =="Friday":
#     print("Access granted")
# else:
#     print("Access denied")


# number= int(input("Enter your number:"))
# if number%2 ==0:
#     print("The number is even")
# else:
#     print("The number is odd")


# number=int(input("Enter number:"))
# if number%3==0:
#     print("The number isdivisible by 3")
# else:
#     print("The number is not divisible by 3")    


# radius=int(input("Enter the radius:"))
# area= (3.14*radius**2 )
# print(f"The area of the circle is {area}")


#    TEST CORRECTIONS

# temperature=float(input("Enter temperature in celsius:")) 
# if temperature<15:
#     print("cold")
# elif(15<=temperature<=30) :
#     print("Moderate")   
# else :
#     print("Hot")    

# for i in range(1,10,2):
#     print(f"Step{i}")


# i = 5 
# while i >= 1:
#     print(i)
#     i -= 1

# for i in range(1,5)  :
#     print(f"{i}, a= {i**2},b={i**3}")



# number = float(input("Enter the number: "))
# #checking if the number is positive
 
# if number > 0:
 
#   print(f"The number is positive.")

# #checking if the number is negative 
  
# elif number < 0:

#    print(f"The number is negative.")

# #checking if the number is zero 
  
# else: 

#    print("The number is zero.")


# i = 1

 
# while i <5:
#     print(i)
#     i +=1

# def average(num1,num2,num3):
#     sum = num1+num2+num3
#     return sum/3
# result= average(20,40,60)
# print(f"{result}")



# my_dict = {"name":"Patience" , "age":25, "city":"Kampala"}
# print(my_dict["city"])


# print(my_dict["age"])

# my_dict["email"]= "nimaropatience@gmail.com"
# print(my_dict)


# del my_dict["age"]
# print(my_dict)



# for key, value in my_dict



my_list = [0, 1, 2, 3, 4, 5, 6, 7, ]

slice = my_list[2:6] 

print(slice)

#Adding elements from a list

my_list = [0, 1, 2, 3, 4, 5]

my_list.append(6)

print(my_list)


#removing elements from a list

# 



# def add_item(list,item):
#     list=[]
#     add_item.append(1)
#     add_item.append(2)
#     add_item.append(3)
#     return list
    
#tuple unpacking
tuple = 1, 2, 3,"Hello"
#Unpacking 
a, b, c ,d= tuple 
print(a, b, c,d)


#split()
#The split() method is used to split a string into a list of substrings based on a specified delimiter.

#join()
#The join() method is used to concatenate a list of strings into a single string with a specified separator.

#replace()
#The replace() method is used to replace occurrences of a substring with another substring in the original string.


#String slicing

text = "Hello, World!"

slice = text[0:5]

print(slice)


#String formatting

name = "John"

age = 30

print("My name is %s and I am %d years old." % (name, age))


#String manipulation

text = "Hello, World!"

print(text.upper())  
                    
                    
                    
                    
                    
                    
                    
                    
                    
 































    






